swagger: '2.0'
info:
  title: exp-starter-api
  version: 0.0.0

tags:
- name: login
  description: Login endpoints
- name: users
  description: User management endpoints
- name: test
  description: Putting tags on your paths objects will organize them in the Swagger UI!
