version: '3.3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: <%= appname %>
  web:
    build: .
    ports:
    - 80:3000
    volumes:
    - .:/usr/src/app
    env_file: .env.example
    environment:
      NODE_ENV: production
    depends_on:
    - postgres
    command: npm start