version: '3.3'
services:
  postgres:
    image: postgres # s:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: <%= appname %>
  web:
    build: .
    ports:
    - 80:3000
    volumes:
    - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/<%= appname %>
      NODE_ENV: production
      JWT_SECRET: secret
    depends_on:
    - postgres
    command: npm start